name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - numpy
  - networkx
  - matplotlib
  - scipy >=1.9.3
  - ipywidgets
  - pip:
    - ./hiperwalk
