name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - ipympl
  - numpy
  - networkx
  - matplotlib
  - scipy
  - pip:
    - hiperwalk
